### ISSUE TITLE
Modify the DocumentTimeline in order to support timeline trigger.

### ISSUE THREAD

**Issue by mantaroh** [theres-waldo/scroll-driven-animations#7]
We should modify the DocumentTimeline in order to support timeline trigger.
This issue is related with Issue #6 

I think that we will need to define the WebIDL as follow:

```
[Func="nsDocument::IsWebAnimationsEnabled",
 Constructor (DOMHighResTimeStamp originTime, optional ScrollTrigger scrollTrigger)]
interface DocumentTimeline : AnimationTimeline {
  readonly attribute ScrollTrigger trigger;
};
```

**Comment by mantaroh** [comment]
In this case, we will need to specify the originTime always even if we want to perform to default document timeline.
Perhaps, some people will not want to specify origin time.  So Should we define first parameter as optional?
If developer doesn't specify the originTime, the value of default document timeline.

``` example
// We should specify the origin time always.
var trigger = new ScrollTrigger(...);
var timeline = new DocumentTimeline(0, trigger);

// If original timer will optional, we won't need to specify origin time.
var trigger = new ScrolLTrigger(...);
var timeline = new DocumentTimeline(trigger);
```

@theres-waldo @birtles
How do you think about this first parameter?

**Comment by mantaroh** [comment]
As discussed with @birtles, We can modify specification of Web Animation Level 1 as following:
- add optional to the origin time.
- or add other constructor which using dictionary.

**Comment by birtles** [comment]
I think we should add a `DocumentTimelineOptions` (dictionary) options argument to level 1 with single member `originTime` the extend it as a partial dictionary in the new spec.

**Comment by mantaroh** [comment]
https://github.com/w3c/web-animations/issues/167

**Comment by theres-waldo** [comment]
In the [latest version of the spec ](https://birtles.github.io/scroll-animations/)we have dropped triggers, so I'm going to close this for now.
